#!/usr/bin/env python3
"""
generate_catalog_appendix.py

Reads batch_output/catalog.csv and produces a LaTeX table snippet
suitable for Appendix B of the paper.

Two outputs:
    * catalog_appendix_short.tex  — First 20 galaxies as a two-page table
    * catalog_appendix_columns.tex — Column-definition table (already in main.tex)
    * catalog_summary.md          — Human-readable summary

Usage:
    python generate_catalog_appendix.py
    # copy catalog_appendix_short.tex into main.tex Appendix B

The full 198-galaxy catalog will be released via Zenodo as
machine-readable CSV/FITS; the appendix snippet just gives a taste
so the reader can see the format.

Author: Abbos Omonov (2026)
"""

import pandas as pd
from pathlib import Path


CATALOG_PATH = "batch_output/catalog.csv"
OUT_TEX = "batch_output/catalog_appendix_short.tex"
OUT_MD  = "batch_output/catalog_summary.md"
N_SHOW = 20


def format_row(row) -> str:
    """Format one CSV row as a LaTeX table row."""
    sid   = int(row["subhalo_id"])
    Mstar = row["M_star_Msun"]                 # in M_sun
    Rd    = row["R_d_kpc"]
    A1m   = row["A1_bootstrap_mean"]
    A1s   = row["A1_bootstrap_std"]
    A2m   = row.get("A2_bootstrap_mean", float("nan"))
    fcoh  = row.get("pattern_coherence", float("nan"))

    # Compact scientific notation for mass
    logM = f"{pd.np.log10(Mstar):.2f}" if hasattr(pd, "np") else f"{Mstar:.2e}"

    return (f"    {sid}  &  "
            f"{Mstar:.2e}  &  "
            f"{Rd:.2f}  &  "
            f"${A1m:.3f} \\pm {A1s:.3f}$  &  "
            f"{A2m:.3f}  &  "
            f"{fcoh:.2f}  \\\\\n")


def main():
    if not Path(CATALOG_PATH).exists():
        print(f"ERROR: {CATALOG_PATH} not found.")
        print("Run this script from your TNGGalaxyLab/batch_tng50 directory.")
        return

    cat = pd.read_csv(CATALOG_PATH)
    print(f"Loaded {len(cat)} rows from {CATALOG_PATH}")

    # Sort by A_1 descending — show interesting galaxies first
    cat_sorted = cat.sort_values("A1_bootstrap_mean",
                                  ascending=False).head(N_SHOW)

    # LaTeX table for Appendix B
    with open(OUT_TEX, "w") as f:
        f.write("% Auto-generated by generate_catalog_appendix.py\n")
        f.write("% Top-20 most lopsided galaxies from the 198-galaxy TNG50 catalog\n\n")
        f.write("\\begin{table*}\n")
        f.write("  \\centering\n")
        f.write("  \\caption{Excerpt from the TNG50 demonstration catalogue, showing\n")
        f.write(f"    the {N_SHOW} most lopsided disc galaxies by bootstrap-mean\n")
        f.write("    $\\Amone$.  The complete 198-galaxy catalogue is available\n")
        f.write("    as a machine-readable file (Zenodo DOI to be assigned).\n")
        f.write("    Bootstrap uncertainties are 1$\\sigma$.}\n")
        f.write("  \\label{tab:catalog_excerpt}\n")
        f.write("  \\begin{tabular}{rccccc}\n")
        f.write("    \\toprule\n")
        f.write("    Subhalo ID  &  $M_\\star$ [$\\Msun$]  &  $\\Rd$ [kpc]  &  "
                "$\\langle \\Amone \\rangle$  &  $\\langle \\Amtwo \\rangle$  &  "
                "$f_{\\rm coh}$ \\\\\n")
        f.write("    \\midrule\n")
        for _, row in cat_sorted.iterrows():
            f.write(format_row(row))
        f.write("    \\bottomrule\n")
        f.write("  \\end{tabular}\n")
        f.write("\\end{table*}\n")

    # Human-readable summary
    with open(OUT_MD, "w") as f:
        f.write(f"# TNG50-1 Demonstration Catalog Summary\n\n")
        f.write(f"**N galaxies:** {len(cat)}\n\n")
        f.write(f"## Statistics\n\n")
        f.write(f"| Quantity | Value |\n|---|---|\n")
        f.write(f"| $A_1$ median | {cat['A1_bootstrap_mean'].median():.3f} |\n")
        f.write(f"| $A_1$ mean   | {cat['A1_bootstrap_mean'].mean():.3f} ± "
                f"{cat['A1_bootstrap_mean'].std():.3f} |\n")
        f.write(f"| $A_1 > 0.1$  | {sum(cat['A1_bootstrap_mean'] > 0.1)} "
                f"({100 * sum(cat['A1_bootstrap_mean'] > 0.1) / len(cat):.1f}%) |\n")
        f.write(f"| $A_1 > 0.2$  | {sum(cat['A1_bootstrap_mean'] > 0.2)} "
                f"({100 * sum(cat['A1_bootstrap_mean'] > 0.2) / len(cat):.1f}%) |\n")
        f.write(f"\n## Champion (most lopsided) galaxies\n\n")
        f.write(cat_sorted[["subhalo_id", "M_star_Msun", "R_d_kpc",
                            "A1_bootstrap_mean", "A1_bootstrap_std"]].to_markdown(
                                index=False))

    print(f"\nAppendix table:    {OUT_TEX}")
    print(f"Summary Markdown:  {OUT_MD}")
    print("\nCopy contents of catalog_appendix_short.tex into main.tex Appendix B.")


if __name__ == "__main__":
    main()
